// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOtsrgPvF8ZVAnyulM6DQBZ2zTa__TZ58',
    appId: '1:809632613285:web:6d5f64c436bbdb62e61e4c',
    messagingSenderId: '809632613285',
    projectId: 'rivala-8efed',
    authDomain: 'rivala-8efed.firebaseapp.com',
    storageBucket: 'rivala-8efed.firebasestorage.app',
    measurementId: 'G-CWMBM8RSGM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC1kVzUg_pPkryXw14bWG8fovP3628R3ac',
    appId: '1:809632613285:android:d7f945867aa1998be61e4c',
    messagingSenderId: '809632613285',
    projectId: 'rivala-8efed',
    storageBucket: 'rivala-8efed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0ijliW-mvFqw5NfRpB0wIn-PMIghTDPk',
    appId: '1:809632613285:ios:0013dbc4a67d6873e61e4c',
    messagingSenderId: '809632613285',
    projectId: 'rivala-8efed',
    storageBucket: 'rivala-8efed.firebasestorage.app',
    iosBundleId: 'com.rivala.RivalaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0ijliW-mvFqw5NfRpB0wIn-PMIghTDPk',
    appId: '1:809632613285:ios:45a55055cbb5ba92e61e4c',
    messagingSenderId: '809632613285',
    projectId: 'rivala-8efed',
    storageBucket: 'rivala-8efed.firebasestorage.app',
    iosBundleId: 'com.example.rivala',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBOtsrgPvF8ZVAnyulM6DQBZ2zTa__TZ58',
    appId: '1:809632613285:web:6890719110cfa9cde61e4c',
    messagingSenderId: '809632613285',
    projectId: 'rivala-8efed',
    authDomain: 'rivala-8efed.firebaseapp.com',
    storageBucket: 'rivala-8efed.firebasestorage.app',
    measurementId: 'G-RYY7HB9FSC',
  );
}
